### ISSUE TITLE
A question about the Q-Former

### ISSUE THREAD

**Issue by Richar-Du** [wangyu-ustc/LVChat#2]
Thanks for your awesome work! I have a question about the number of embedding encoded by the Q-Former.

Section 4.1 states that N=96, but VideoChat2 only uses 32 query embeddings during training. Did you initialize the 96-32=64 query embeddings randomly? If this is true, why not just use the original 32 embeddings? I think introduce another 64 random embeddings may hurt the original model performance. Thanks in advance :)

@wangyu-ustc

**Comment by wangyu-ustc** [comment]
Please check the file `scripts/config_7b_stage3.py` in the original VideoChat2 repo, where they have "num_query_token=32" and "extra_num_query_token=64". Thus they actually have 96 query tokens in total. We directly follow their design and initialize from their model weights.

**Comment by Richar-Du** [comment]
Got it, thanks for your reply.
